### ISSUE TITLE
HttpResolverTests that use sslResource require acdc.amherst.edu certificate in keystore

### ISSUE THREAD

**Issue by christopher-johnson** [trellis-ldp/trellis-http#3]
when I run the tests with the JDK-9 VM, (for example, by using ./gradlew test), it throws an javax.net.ssl.SSLHandshakeException.  

A portable fix is to add the certificate to a keystore in resources and then set test to read it:
```groovy
test {
  systemProperty 'javax.net.ssl.trustStore', 'trellis.cacerts'
}
```
I fixed it locally by adding the acdc.amherst.edu to my keystore with this command:
`$ sudo keytool -import -alias amherst -keystore /usr/lib/jvm/jdk-9/lib/security/cacerts -file acdc.amherst.edu`

**Comment by acoburn** [comment]
It might make more sense to use a domain that doesn't require modification of the cacert config.

**Comment by christopher-johnson** [comment]
A local keystore would be an issue for a self-signed TLS certificate that might be used in mockserver CI testing as well.   I think that it might be useful to have a keystore artifact for trellis testing.  And I like the idea of depending on localhost as less as possible.

**Comment by acoburn** [comment]
I am going to close this particular issue but leave https://github.com/trellis-ldp/trellis-vocabulary/issues/1 open, as I have consolidated the SSL tests to just the `.w3.org` and `.amazonaws.com` domains. The underlying requirement of a valid keystore for testing is still an issue.
