### ISSUE TITLE
feature request: PUT request with empty body creates container

### ISSUE THREAD

**Issue by christopher-johnson** [trellis-ldp/trellis-http#4]
The Fedora REST API allows a request like this:

`curl -i -X PUT "http://localhost:8080/rest/node/to/create"`

to create "http://localhost:8080/rest/" and "http://localhost:8080/rest/node" and "http://localhost:8080/rest/node/to" and "http://localhost:8080/rest/node/to/create" if they do not exist.

I have looked at the PutHandler, but am not sure how to implement this.  It seems that the handler requires an entity body (and not just the identifier) to create a resource.

It seems practical to implement a method that allows for simple "empty body" container creation.  Is there another method to just create an "empty" container?

**Comment by ajs6f** [comment]
TBC, @christopher-johnson, you just want to create resources by using an empty body? You're not asking for recursive creation, right?

**Comment by christopher-johnson** [comment]
Upward ancestor container creation, if they do not exist.  Not really recursion I guess.  I change the title.

So for example, a PUT request with an empty body to http://example.org/repo/x/y/z creates containers z -> y -> x.

**Comment by ajs6f** [comment]
That is _hugely_ problematic for distributed implementations. 👎

**Comment by christopher-johnson** [comment]
um. ok.  can you explain why fcrepo does i?t

**Comment by ajs6f** [comment]
FCREPO made plenty of poor decisions, especially around distribution. Those decisions were a major impetus for @acoburn to start the Trellis project.

**Comment by christopher-johnson** [comment]
I also looked that the HTTP 1.1 spec about PUT (9.6) and it says: 

> the URI in a PUT request identifies the entity enclosed with the request -- the user agent knows what URI is intended and the server MUST NOT attempt to apply the request to some other resource

So, I agree with following the spec, that does not seem to allow such action, technically.  Is is legal to PUT empty body even?

**Comment by ajs6f** [comment]
Yes, and it's a good restriction (to which you refer) because a request at one resource causing action at a distant resource is a bit unRESTful.

As for empty `PUT` body, I think it's a question of media type. Is an empty body an intelligible representation for whatever media type is indicated? For example, in NTriples, an empty stream of triples is A-OK, no problem. It's just an empty graph. If I then `GET` that resource with an `Accept` of `application/rdf+xml` I can get a pretty obvious representation: something like `<rdf:Description rdf:about="http://my/resource"/>`. So at least for LDP-RSes, it seems reasonable to me. As for other media types... maybe it's a bit more subtle. 

Think about the round trip-- let's say I create a JPEG2k LDP-NR by using an empty body `PUT`. I'm no expert on JPEG2k, but I understand that it features some headers (not HTTP headers, headers inside the file). Is is possible for the repo to develop reasonable default values for those headers? If not, when I `GET` the resource, I expect to get a JPEG2k, but what are the values of those media-type-specific headers?

**Comment by christopher-johnson** [comment]
hmm, I just tried this:
```bash
curl -X PUT -H "Content-Type: text/turtle" --data-binary "@emptyData.txt" "http://localhost:8080/repository/node/collection/test"
```

without having created `node` or `collection`, and Trellis accepted it.  So, it seems that Trellis also creates ancestors, if they do not exist.  The solution seems to be simply include an empty file with the request.

**Comment by ajs6f** [comment]
I think auto-creating ancestors would have required some work on @acoburn's part, so let's wait for him to comment. He may not be looking at this until after the weekend.

**Comment by christopher-johnson** [comment]
actually you are right, `node` and `collection` are not created, but the resource is allowed to be orphaned, which is fine with me, as long as it has the correct path semantics.

**Comment by ajs6f** [comment]
Oh-- I think I see-- we may have been talking past one another.

We didn't distinguish at the start of the conversation between creating segments in an URI's path, and creating LDP resources addressable at those segments (so to speak). I thought you were asking to have LDP resources created, but I think perhaps now I misunderstood? You just want to be able to use the URI you want (with all of its path) _without_ creating those intermediate resources?

**Comment by christopher-johnson** [comment]
correct.  I think that this feature request is invalid per 9.6 of the HTTP 1.1 spec. that references the "entity enclosed with the request" which to me, means that it must be there.  I close this issue.

**Comment by ajs6f** [comment]
Well, now I actually think that there are two things here-- empy-body `PUT`, and using `PUT` without creating a bunch of intermediate resources, and actually I think (as discussed above) we could find reasonable ways to do (at least part of) either (it was the creation of intermediating resources that I found problematic, but that's not something for which you were actually asking), but as you wish.

**Comment by acoburn** [comment]
Just to chime in here after the fact -- recursive PUT or the creation of intermediate, non-existent containers is not something that Trellis supports. I am happy to explain why, but it's a little involved and it has to do with distributed architectures and concurrent requests to create such intermediate containers. Basically, as @ajs6f already mentioned, the creation of intermediate containers is really problematic. With Trellis, a client needs to manage such things itself (I really don't think such a requirement is so onerous, though). And yes, it is entirely possible to create a resource at `/node/collection/test` without having first created `/node` or `/node/collection`. It is furthermore possible for a client to create a LDP-NR at `/node/collection` (there will *not* be an ldp:contains triple pointing at `/node/collection/test`), though that's kind of a silly thing for a client to do. 

Basically, Trellis does not provide a lot of restrictions on what a client can and cannot do -- a client is perfectly capable of writing all sorts of nonsensical data into the datastore, but this is where I've taken the approach that it's up to the client application to follow best practices, it's not the responsibility of the repository to force the client to model resources in a particular way (maybe there are good reasons a client is doing what it's trying to do). For example, what if a RDBMS enforced the fifth normal form on client data modeling? That would be pretty restrictive even if it is a good practice.

As for creation of resources with an empty body, there are a few things going on -- first, the best way to create resources is with a `Link: <LDP-TYPE>; rel="type"` header. In the absence of that header, Trellis tries to guess what the client means, based on the `Content-Type` header. Absent both of those, it's admittedly a little hard to guess what a client means. I *think* that in that situation, a 4xx response is returned. I also thought that an empty body PUT is supported, both for LDP-RS (so long as the content-type supports such a thing) and LDP-NR resources.

**Comment by ajs6f** [comment]
I'm still weirded out by the idea that you could `PUT` an empty stream as (say) a PDF and then get it and it's an empty stream, which isn't a PDF. But I guess that all comes under the same heading as @acoburn gave above-- clients can do whatever they want. It's not the server's job to make the client make sense.
